### ISSUE TITLE
remove redundant information from TOML files

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#66]
like version, repo URL, name etc.

from

- [x] template
- [x] example manifest files (OHLOOM)

**Comment by moedn** [comment]
whatever can be taken from the 'mother' `okh.toml` file or the `sBoM.csv` should be. In the case of `okh-ClampRing.toml` we are left with

``` toml
okhv = "2.0"
image = "/Documentation/Assembly_Guide/Parts_Print_2.jpg"
tsdc-id = "COM-MAN"
production-metadata = [ "3D printed", "PLA", "cylinder(h=30, r=28)" ]
source = "/3DParts/ClampRing/ClampRing.scad"
export = [
  "/3DParts/ClampRing/ClampRing.pdf",
  "/3DParts/ClampRing/ClampRing.stl"
]
```
